# -*- coding: utf-8 -*-
"""MIT_DeepLearning_LabPart2_PyTorch (AI-Music Generation)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19h_hiKGVqDOy1Q4_rKWqEQy2IqoLNsRm

# AI Music Generation with RNNs
**Context**: MIT 6.S191 Deep Learning Lab

**Objective**: Developing a Recurrent Neural Network (RNN) to predict and generate musical notes in ABC notation.

**Key Concepts**: Embedding Layers, GRU/LSTM Units, Multinomial Sampling, and Audio Waveform Synthesis.
"""

# Download and install comet_ml
!pip install comet_ml --quiet

import comet_ml
# TODO: ENTER YOUR API KEY HERE!! instructions above
COMET_API_KEY = "nb70UBQI77F7RAR68p5njFEyz"

# Import PyTorch and other relevant libraries
import torch
import torch.nn as nn
import torch.optim as optim

# Download and import the MIT Introduction to Deep Learning package
!pip install mitdeeplearning --quiet
import mitdeeplearning as mdl

# Import all remaining packages
import numpy as np
import os
import time
import functools
from IPython import display as ipythondisplay
from tqdm import tqdm
from scipy.io.wavfile import write
!apt-get install abcmidi timidity > /dev/null 2>&1


# Check that we are using a GPU, if not switch runtimes
#   using Runtime > Change Runtime Type > GPU
assert torch.cuda.is_available(), "Please enable GPU from runtime settings"
assert COMET_API_KEY != "", "nb70UBQI77F7RAR68p5njFEyz"

!pip install comet_ml

"""# Downloading the dataset"""

songs = mdl.lab1.load_training_data()

# Print one of the songs to inspect it in greater detail!
example_song = songs[0]
print("\nExample song: ")
print(example_song)

mdl.lab1.play_song(example_song)

# Join our list of song strings into a single string containing all songs
songs_joined = "\n\n".join(songs)

# Find all unique characters in the joined string
vocab = sorted(set(songs_joined))
print("There are", len(vocab), "unique characters in the dataset")

"""songs_joined = "\n\n".join(songs)
songs: Yeh hamari list thi jis mein hazaron alag alag gaane thay.

"\n\n": Iska matlab hai "Double New Line" (yani do baar Enter dabana).

.join(): Yeh Python ka ek function hai jo list ki saari cheezon ko aapas mein jod deta hai.
vocab = sorted(set(songs_joined))
Yahan teen bade kaam ho rahe hain (Right se Left parho):

set(songs_joined): set ka kaam hai duplicate khatam karna. Gaane mein hazaron baar 'A' ya 'B' aaya hoga, lekin set usey sirf aik baar ginega. Is se humein milte hain "Unique Characters".

sorted(...): Yeh un unique characters ko tartib (A, B, C... ya 1, 2, 3...) de deta hai.

vocab: Ise hum "Vocabulary" (Zakhira-e-Alfaaz) kehte hain. Yeh woh list hai jo batati hai ke hamare poore data mein kul kitne qism ke nishanat (letters, numbers, symbols) istemal hue hain.

# Translator (Vectorize the text)
Before we begin training our RNN model, we'll need to create a numerical representation of our text-based dataset. To do this, we'll generate two lookup tables: one that maps characters to numbers, and a second that maps numbers back to characters. Recall that we just identified the unique characters present in the text.
"""

### Define numerical representation of text ###

# Create a mapping from character to unique index.
# For example, to get the index of the character "d",
#   we can evaluate `char2idx["d"]`.
char2idx = {u: i for i, u in enumerate(vocab)}

# Create a mapping from indices to characters. This is
#   the inverse of char2idx and allows us to convert back
#   from unique index to the character in our vocabulary.
idx2char = np.array(vocab)

"""char2idx = {u: i for i, u in enumerate(vocab)}
Yeh line ek Dictionary bana rahi hai jo Character ko Number mein badal deti hai.

vocab: Yeh hamari unique characters ki list thi (e.g., ['A', 'B', 'C']).

enumerate(vocab): Yeh function har character ko ek "Roll Number" (index) de deta hai. Jaise: (0, 'A'), (1, 'B'), (2, 'C').

{u: i for i, u in ...}: Yeh Python ka "Dictionary Comprehension" hai. Yeh keh raha hai: "Ek dictionary banao jahan character (u) key ho aur uska number (i) value ho."

Natija (Example): Agar aap char2idx['A'] likhenge, to computer jawab dega 0.

2. idx2char = np.array(vocab)
Yeh uska Ulta (Inverse) hai. Iska kaam hai Number se wapas Character nikalna.

np.array(vocab): Humne apni vocabulary ko ek NumPy Array mein badal diya.

Kyun?: Array ka faida ye hai ke agar hum kahein idx2char[0], to woh foran humein us index par maujood character (yaani 'A') nikaal kar de dega.
"""

print('{')
for char, _ in zip(char2idx, range(90)):
    print('  {:4s}: {:3d} '.format(repr(char), char2idx[char]))
print('  ...\n}')

"""Sochiye hamare paas ye template hai: [ Name ] : [ Roll No ]

Agar hum likhein .format("Ali", 10), to output aayega: Ali : 10

Yahan bhi wahi ho raha hai: [ repr(char) ] : [ char2idx[char] ]
[ repr(char) ] ye line character ki asal shakal dikhai
[ char2idx[char] ] ye char ka index btaigi jo humny khud bnaya tha

"""

### Vectorize the songs string ###

'''TODO: Write a function to convert the all songs string to a vectorized
    (i.e., numeric) representation. Use the appropriate mapping
    above to convert from vocab characters to the corresponding indices.

  NOTE: the output of the `vectorize_string` function
  should be a np.array with `N` elements, where `N` is
  the number of characters in the input string
'''
def vectorize_string(string):
  vectorized_output = np.array([char2idx[char] for char in string])
  return vectorized_output

# def vectorize_string(string):
  # TODO

vectorized_songs = vectorize_string(songs_joined)

"""def vectorize_string(string):
Yahan hum ek function bana rahe hain. Iska maqsad ye hai ke hum ise koi bhi text (string) dein, aur ye badle mein humein us text ke Numbers (Vector) de de.

2. vectorized_output = np.array([char2idx[char] for char in string])
Yeh is function ki sab se aham line hai. Ismein teen bade kaam ho rahe hain:

for char in string: Yeh loop input string (hamare gaane) mein se ek ek character uthata hai.

char2idx[char]: Yeh us character ko hamari banayi hui dictionary mein dhoondta hai aur uska Index (Number) nikal leta hai.

np.array([...]): Yeh un saare numbers ko ek list mein jama karta hai aur phir usey NumPy Array mein badal deta hai. NumPy array is liye zaroori hai kyunke AI models is par bohot tezi se calculations karte hain.
vectorized_songs = vectorize_string(songs_joined)
Yahan hum us function ko Call kar rahe hain.

songs_joined: Yeh hamari woh "Lambi Kitaab" hai jis mein saare gaane aik sath jure hue hain.

Hamara function is poori kitaab ko parhega aur har har lafz ko number mein badal kar vectorized_songs mein store kar dega.
"""

print ('{} ---- characters mapped to int ----> {}'.format(repr(songs_joined[:10]), vectorized_songs[:10]))
# check that vectorized_songs is a numpy array
assert isinstance(vectorized_songs, np.ndarray), "returned result should be a numpy array"

### Batch definition to create training examples ###

def get_batch(vectorized_songs, seq_length, batch_size):
    # the length of the vectorized songs string
    n = vectorized_songs.shape[0] - 1
    # randomly choose the starting indices for the examples in the training batch
    idx = np.random.choice(n - seq_length, batch_size)

    '''TODO: construct a list of input sequences for the training batch'''
    input_batch = [vectorized_songs[i: i + seq_length] for i in idx]

    '''TODO: construct a list of output sequences for the training batch'''
    output_batch = [vectorized_songs[i + 1: i + seq_length + 1] for i in idx]

    # Convert the input and output batches to tensors
    x_batch = torch.tensor(input_batch, dtype=torch.long)
    y_batch = torch.tensor(output_batch, dtype=torch.long)

    return x_batch, y_batch

# Perform some simple tests to make sure your batch function is working properly!
test_args = (vectorized_songs, 10, 2)
x_batch, y_batch = get_batch(*test_args)
assert x_batch.shape == (2, 10), "x_batch shape is incorrect"
assert y_batch.shape == (2, 10), "y_batch shape is incorrect"
print("Batch function works correctly!")

"""def get_batch(vectorized_songs, seq_length, batch_size):

def: Yeh Python ka lafz hai jo batata hai ke hum ek Function (aik kaam karne wali machine) bana rahe hain.

get_batch: Yeh is function ka Naam hai.

vectorized_songs: Yeh hamara Data hai. Ismein saare gaane numbers ki surat mein maujood hain.

seq_length: Yeh aik Sawal ki Lambai hai. Maslan, agar hum AI ko aik waqt mein 100 characters dikhana chahte hain, to seq_length 100 hogi.

batch_size: Yeh batata hai ke AI aik saath Kitni Misalein (examples) dekhega. Agar yeh 64 hai, to AI aik hi waqt mein 64 mukhtalif jaghon se seekhega.

Doosri Line (Length nikalna):
n = vectorized_songs.shape[0] - 1

n: Yeh ek variable hai jismein hum total characters ki ginti save kar rahe hain.

shape[0]: Yeh batata hai ke hamare poore data mein Total kitne numbers hain.

- 1: Yeh humne isliye kiya kyunke humein hamesha Agla (Next) character predict karna hota hai. Agar hum bilkul aakhri number par kharay honge, to usse agay koi "Jawab" dene ke liye bachega hi nahi.

Teesri Line (Random Jagah Chun-na):
idx = np.random.choice(n - seq_length, batch_size)

idx: Iska matlab hai Index. Yeh woh points hain jahan se hum tukra kaatna shuru karenge.

np.random.choice: Yeh NumPy ka tool hai jo Random (kahin se bhi) numbers chunta hai.

n - seq_length: Yeh had (boundary) hai. Hum random number itna agay se nahi chun sakte ke aage 100 characters ki jagah hi na bache.

batch_size: Yeh batata hai ke humein kitne random starting points chahiye. Agar batch_size 2 hai, to yeh 2 random jaghen chune ga.

Ch चौथी Line (Input Tukra Kaatna):
input_batch = [vectorized_songs[i: i + seq_length] for i in idx]

input_batch: Yeh hamare Sawalon ki list hai.

[ ... for i in idx]: Yeh aik loop hai jo har chune hue random point (i) par jata hai.

vectorized_songs[i : i + seq_length]: Yeh asli "Cutting" hai. Yeh index i se shuru hota hai aur wahan se seq_length jitne characters utha leta hai.

Asaan Misaal (Analogy):
Maano ke aapke paas aik lambi Rassi (Rope) hai aur aapne usmein se 2 tukre kaatne hain:

Pehle aapne aankhein band karke 2 jaghen chuni (idx).

Phir har jagah se aapne 10 inch ka tukra kaat liya (seq_length).

Ab aapke paas 2 tukre hain jo AI ko sikhane ke kaam aayenge (input_batch).
1. Output Batch (Jawab/Target)
output_batch = [vectorized_songs[i + 1: i + seq_length + 1] for i in idx]

i + 1: Yeh sab se zaroori baat hai. Input i se shuru hua tha, magar Output ek qadam agay se shuru ho raha hai.

i + seq_length + 1: Kyunke shuruat ek qadam agay se hui, isliye khatam bhi ek qadam agay hi hoga taake lambai (seq_length) barabar rahe.

Maqsad: AI ko yeh sikhana hai ke agar pehla character X hai, to agla character kya hona chahiye.

Input: "P-Y-T-H-O"

Output: "Y-T-H-O-N" (Dekhein, har character ka "Target" usse agla wala character ban gaya hai).

2. Tensors mein Tabdeeli (AI ki Khorak)
x_batch = torch.tensor(input_batch, dtype=torch.long) y_batch = torch.tensor(output_batch, dtype=torch.long)

torch.tensor: Computer ki simple list par AI model train nahi ho sakta. PyTorch ko Tensors chahiye hote hain (jo matrix ki tarah hote hain). Yeh line hamari list ko PyTorch ke format mein badal rahi hai.

dtype=torch.long: Yeh batata hai ke hamara data Integers (poore numbers jaise 1, 2, 3) ki surat mein hai. Long ka matlab hai "bade integers" taake koi error na aaye.

x_batch: Hamare saare Sawal (Inputs).

y_batch: Hamare saare Jawab (Targets).

3. Return (Bahar Nikalna)
return x_batch, y_batch

return: Yeh function ko khatam karta hai aur jo humne x_batch aur y_batch banaye hain, unhein function se bahar nikaal deta hai taake hum unhein training mein use kar saken.
1. Test Input Tayyar Karna
test_args = (vectorized_songs, 10, 2)

Yahan humne teen values ka ek set banaya hai.

vectorized_songs: Poora dataset (numbers).

10: Hamari seq_length (yani ek sawal 10 numbers lamba ho).

2: Hamara batch_size (yani humein 2 sawal/jawab ke jode chahiye).

2. Function ko Run Karna
x_batch, y_batch = get_batch(*test_args)

Yeh line hamare function ko upar wali values ke saath chalati hai.

*test_args: Yeh jo * (asterisk) hai, yeh aik shortcut hai. Iska matlab hai ke test_args ke andar maujood teeno cheezon ko bari bari function mein bhej do.

Ab x_batch mein 2 sawal hain aur y_batch mein unke 2 jawab.

3. Check Point (Assert Statements)
assert x_batch.shape == (2, 10), "x_batch shape is incorrect"

assert: Yeh Python ka aik guard hai. Iska matlab hai "Check karo ke kya yeh baat sach hai?"

.shape: Yeh check karta hai ke matrix ka size kya hai.

(2, 10): Iska matlab hai 2 Rows (Batch size) aur 10 Columns (Sequence length).

Logic: Agar function ne sahi kaam kiya hai to size (2, 10) hi hona chahiye. Agar size kuch aur hua (maslan 2 rows na hui), to code ruk jayega aur error message dega: "x_batch shape is incorrect".

assert y_batch.shape == (2, 10), "y_batch shape is incorrect"

Yeh wahi check Jawab (Target) ke liye bhi kar raha hai.

4. Kamyabi ka Message
print("Batch function works correctly!")

Agar dono assert statements sahi nikli (yani koi error nahi aaya), to Python is aakhri line par ayega aur yeh message print karega. Iska matlab hai ke ab aapka data model ko sikhane ke liye bilkul tayyar hai.
"""

x_batch, y_batch = get_batch(vectorized_songs, seq_length=7, batch_size=2)

for i, (input_idx, target_idx) in enumerate(zip(x_batch[0], y_batch[0])):
    print("Step {:3d}".format(i))
    print("  input: {} ({:s})".format(input_idx, repr(idx2char[input_idx.item()])))
    print("  expected output: {} ({:s})".format(target_idx, repr(idx2char[target_idx.item()])))

"""x_batch, y_batch = get_batch(vectorized_songs, seq_length=5, batch_size=1)

x_batch, y_batch: Yeh do dabbe (variables) hain. x mein hum ne sawal rakha aur y mein uska jawab.

get_batch(...): Yeh woh function hai jo hum ne upar likha tha, jo rassi (data) mein se tukre kaat-ta hai.

seq_length=5: Hum ne kaha ke sirf 5 characters lamba tukra kaato.

batch_size=1: Hum ne kaha ke abhi sirf aik (1) misaal dikhao taake hum asani se samajh saken.

2. Doosri Line: Loop aur Pairing
for i, (input_idx, target_idx) in enumerate(zip(x_batch[0], y_batch[0])):

for ... in: Yeh Python ka loop hai jo bari bari har character par jayega.

enumerate: Yeh ginti (counting) karta hai: 0, 1, 2, 3, 4. Is ginti ko hum ne i ka naam diya hai.

zip: Yeh sab se mazedar cheez hai. Yeh do lists ko aamne-saamne jorh deta hai.

Sawal ka pehla lafz + Jawab ka pehla lafz.

Sawal ka doosra lafz + Jawab ka doosra lafz.

x_batch[0], y_batch[0]: Chunke hamara batch_size 1 tha, is liye hum sirf pehli row (index 0) utha rahe hain.

input_idx, target_idx: Yeh hamare temporary naam hain. input_idx mein sawal wala number aayega aur target_idx mein jawab wala number.

3. Teesri Line: Step Number Print Karna
print("Step {:3d}".format(i))

"Step {:3d}": Yeh aik design (template) hai. {:3d} ka matlab hai ke yahan aik number aayega jo kam az kam 3 spaces ki jagah lega.

.format(i): Yeh batata hai ke us design mein i (yani 0, 1, 2...) ki value daal do.

Output: Step 0, Step 1, etc.

4. Chouthi Line: Input (Sawal) Dikhana
print(" input: {} ({:s})".format(input_idx, repr(idx2char[input_idx.item()])))

input_idx: Woh number jo AI dekh raha hai.

idx2char: Hamari dictionary jo number ko wapas Lafz (Character) mein badalti hai.

.item(): PyTorch ke tensor se sirf woh akela number nikalne ke liye.

repr(...): Yeh character ko saaf dikhane ke liye hai (maslan agar newline \n ho to woh nazar aa jaye).

Output: input: 15 ('A') (Misaal ke taur par).

5. Paanchvi Line: Target (Jawab) Dikhana
print(" expected output: {} ({:s})".format(target_idx, repr(idx2char[target_idx.item()])))

expected output: Yani AI ko is sawal par kya jawab dena chahiye tha.

Baaqi sab kuch wahi hai jo upar wali line mein tha, bas yahan hum agla character dikha rahe hain.

Asaan Khulasa (Summary):
Yeh code screen par kuch aisa dikhayega (farz karein music ka data "ABCDE" hai):

Step 0: Input: 'A', Expected Output: 'B'

Step 1: Input: 'B', Expected Output: 'C'

Step 2: Input: 'C', Expected Output: 'D'

Step 3: Input: 'D', Expected Output: 'E'

Iska matlab hai ke AI sikh raha hai ke 'A' ke baad 'B' aata hai, aur 'B' ke baad 'C' aata hai.

# The Recurrent Neural Network (RNN) model
nn.Embedding (The Translator)
Computer alphabet ('A', 'D') ya sirf numbers (26, 29) ko achi tarah nahi samajhta. Woh chahta hai ke har character ke paas uski apni aik "shakhsiyat" (personality) ho.

Kaam: Yeh layer har number ko aik lambay Vector (numbers ki list) mein badal deti hai.

Misaal: Agar 'A' ka number 26 hai, to Embedding usay [0.12, -0.5, 0.8...] mein badal degi.

Fayda: Is se AI ko yeh samajhne mein madad milti hai ke kaunse characters aapas mein milte jultay hain (maslan music mein 'A' aur 'a' shayad milte jultay hon).

2. nn.LSTM (The Brain with Memory)
Yeh hamare model ka sab se zaroori hissa hai. Aam Neural Network (Simple NN) purani baatein bhool jata hai, lekin LSTM (Long Short-Term Memory) ko yaad rehta hai.

Kaam: Jab hum isay pehla note 'A' dete hain, to yeh usay aik "State Vector" (Memory) mein save kar leta hai.

Temporal Relationship: Jab agla note 'D' aata hai, to LSTM ko yaad hota hai ke "Pichli baar 'A' aaya tha, ab 'D' aaya hai, to shayad agla note phir se 'D' ho."

Memory: Yeh "State Vector" hi woh cheez hai jo gaane ki dhun aur rhythm ko yaad rakhti hai.

3. nn.Linear (The Final Decision)
LSTM ne apna kaam kar diya, ab faisla sunane ki baari hai.

Kaam: LSTM ki memory se jo result nikalta hai, yeh layer usay wapas Vocab Size (hamare total characters ki ginti) mein badal deti hai.

Softmax: Yeh har character ko aik "Probability" (chance) deti hai.

Maslan: 'D' ka chance 80%, '2' ka chance 15%, 'F' ka chance 5%.

Sampling: Hum sab se zyada chance wale character (ya random chance ke mutabiq) ko chunte hain aur wahi hamara Next Character hota hai.
RNN Model kaam kaise karta hai? (Full Picture)
Input: Aap ne AI ko character 'A' diya (Number 26).

Embedding: 'A' ban gaya aik Vector.

LSTM: LSTM ne dekha ke abhi 'A' baja hai aur apni memory update ki.

Linear: Is ne probability nikaali ke agla note kya hoga.

Output: AI ne kaha "Agla note 'D' hai."

Loop: Ab yeh 'D' wapas model mein jayega aur AI agla note predict karega. Is tarah poora gaana banta hai!
"""

class LSTMModel(nn.Module):
    def __init__(self, vocab_size, embedding_dim, hidden_size):
        super(LSTMModel, self).__init__()
        self.hidden_size = hidden_size

        # Define each of the network layers
        # Layer 1: Embedding layer to transform indices into dense vectors
        #   of a fixed embedding size
        self.embedding = nn.Embedding(vocab_size, embedding_dim)

        # Layer 2: LSTM with hidden_size `hidden_size`. note: number of layers defaults to 1.
        # TODO: Use the nn.LSTM() module from pytorch.
        self.lstm = nn.LSTM(embedding_dim, hidden_size, batch_first=True)
        # self.lstm = nn.LSTM('''TODO''')

        # Layer 3: Linear (fully-connected) layer that transforms the LSTM output
        #   into the vocabulary size.
        # TODO: Add the Linear layer.
        self.fc = nn.Linear(hidden_size, vocab_size)
        # self.fc = nn.Linear('''TODO''')

    def init_hidden(self, batch_size, device):
        # Initialize hidden state and cell state with zeros
        return (torch.zeros(1, batch_size, self.hidden_size).to(device),
                torch.zeros(1, batch_size, self.hidden_size).to(device))

    def forward(self, x, state=None, return_state=False):
        x = self.embedding(x)

        if state is None:
            state = self.init_hidden(x.size(0), x.device)
        out, state = self.lstm(x, state)

        out = self.fc(out)
        return out if not return_state else (out, state)

"""---

### Block 1: The Blueprint (`__init__`)

Yahan hum machine ke purze (parts) define karte hain.

* **`self.embedding = nn.Embedding(vocab_size, embedding_dim)`**
* **Word Impact:** `vocab_size` (83 characters)  `embedding_dim` (256 numbers).
* **Concept:** Ye **Translator** hai. Deep learning mein characters (A, B, C) computer ko samajh nahi aate, isliye ye unhein "meaningful numbers" mein badal deta hai.
* **Output Effect:** Iske baghair AI ko ye nahi pata chalega ke 'A' aur 'a' mein kya rishta hai.


* **`self.lstm = nn.LSTM(embedding_dim, hidden_size, batch_first=True)`**
* **Word Impact:** `hidden_size` (Dimaag ki taqat).
* **Concept:** Ye **Yaad-daasht (Memory)** hai. Ye pichle notes ko yaad rakhta hai taake music ka flow bana rahe.
* **Output Effect:** Iske baghair AI har note ko random bajayega (Be-sura music).


* **`self.fc = nn.Linear(hidden_size, vocab_size)`**
* **Word Impact:** `hidden_size`  `vocab_size`.
* **Concept:** Ye **Final Judge** hai. LSTM ne jo idea socha, ye usay wapas "Lafz" (Character) mein badalta hai.



---

### Block 2: Fresh Start (`init_hidden`)

Jab AI naya gaana shuru kare to dimaag saaf hona chahiye.

* **`torch.zeros(1, batch_size, self.hidden_size)`**
* **Concept:** Ye AI ko **Do Khali Notebooks** (Hidden state aur Cell state) deta hai.
* **Impact:** Agar ye 0 na hon, to naye gaane mein pichle gaane ka kachra (noise) aa jayega.
* **`.to(device)`**: Iska impact ye hai ke agar training GPU par hai, to notebooks bhi wahin honi chahiye, warna code crash ho jayega.



---

### Block 3: The Flow (`forward`)

Ye batata hai ke data model ke andar kaise move karega.

1. **`x = self.embedding(x)`**: Pehle lafz ka **Matlab** nikala gaya.
2. **`if state is None`**: Agar dimaag khali hai, to **Nayi Notebooks** (`init_hidden`) le aao.
3. **`out, state = self.lstm(x, state)`**: Matlab aur Notebook ko LSTM ko diya. LSTM ne purani baat yaad ki, naya note samjha, aur **Notebook update** kar li.
4. **`out = self.fc(out)`**: LSTM ke "khayal" ko Linear layer ne **Scores** mein badal diya (ke 'A' ka 90% chance hai, 'B' ka 2%...).
5. **`return out...`**: Faisla bahar bhej diya.

---

### 💡 Summary Concept (MIT Style)

Socho tum ek music paper par likh rahe ho:

1. **Embedding:** Tumne ek note dekha.
2. **LSTM:** Tumne pichle 5 notes yaad kiye aur dimaag mein rhythm banayi.
3. **Linear (fc):** Tumne pen uthaya aur agla note likh diya.
4. **State:** Tumne agle note ke liye pichli dhun yaad rakhi.

"""

# Instantiate the model! Build a simple model with default hyperparameters. You
#     will get the chance to change these later.
vocab_size = len(vocab)
embedding_dim = 256
hidden_size = 1024
batch_size = 8

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

model = LSTMModel(vocab_size, embedding_dim, hidden_size).to(device)

# print out a summary of the model
print(model)

"""Class Definition aur Initialization (__init__)
Python

class LSTMModel(nn.Module):
    def __init__(self, vocab_size, embedding_dim, hidden_size):
        super(LSTMModel, self).__init__()
        self.hidden_size = hidden_size
class LSTMModel(nn.Module): Hum PyTorch ko bata rahe hain ke hum ek naya neural network model bana rahe hain jo nn.Module ki khasiyatain inherit (virsay mein lena) karega. 🏗️

__init__: Ye model ka blueprint hai. Jab hum model banate hain, to ye function layers ko set up karta hai.

vocab_size: Ye aapki music library mein maujood kul alag-alag notes (tunes) ki tadat hai.

embedding_dim: Har note ko kitne numbers (features) se represent kiya jaye.

hidden_size: LSTM ke andar kitne "yaadshat" wale units honge.

2. Layers ka Setup
Embedding Layer 🗺️
self.embedding = nn.Embedding(vocab_size, embedding_dim) Computer notes ko direct nahi samajh sakta. Ye layer har note (jo ek number hota hai) ko ek lambi list of numbers (vector) mein badal deti hai taake model unke darmiyan rishta samajh sake.

LSTM Layer 🧠
self.lstm = nn.LSTM(embedding_dim, hidden_size, batch_first=True) Ye model ka dimagh hai. Ye pichle notes ko yaad rakhta hai taake agla note music ke hisab se sahi ho.

batch_first=True: Iska matlab hai hamara data is shakal mein hoga: (Batch Size, Sequence Length, Features).

Linear (Fully Connected) Layer 🎹
self.fc = nn.Linear(hidden_size, vocab_size) LSTM ne jo seekha, ye layer usay wapas hamari vocabulary mein convert karti hai. Ye har note ko ek "score" deti hai ke agla note hone ka kitna chance hai.

(embedding): Embedding(83, 256)
Lafzi Matlab: Aapka "Translator" (Embedding layer) tayyar hai.

Numbers ka Impact: * 83: Iska matlab hai aapke paas total 83 characters (A, B, C, symbols, numbers) hain.

256: Har character ko 256 numbers ki aik "shakhsiyat" (vector) di jayegi.

Deep Learning Concept: AI ne 83 alag alag cheezon ko pehchanna hai. Agar aap input mein koi 84th character (jo dictionary mein nahi hai) dalenge, to model crash ho jayega kyunke uske pas sirf 83 ki jagah hai.

2. (lstm): LSTM(256, 1024, batch_first=True)
Lafzi Matlab: Aapka "Dimaag/Memory" (LSTM layer) set hai.

Numbers ka Impact:

256: Isay input mein wahi 256 numbers milenge jo Embedding layer ne banaye thay. (Inka match hona zaroori hai).

1024: Ye dimaag ki capacity hai. LSTM ke paas 1024 hidden units hain jo music ke patterns yaad rakhenge.

batch_first=True: Iska matlab hai data "Groups" (batches) ki surat mein move karega.

Deep Learning Concept: Ye model kafi "Smart" hai kyunke 1024 ka hidden size kafi bada hota hai. Ye lambi sequences (long melodies) yaad rakhne ke qabil hai.

3. (fc): Linear(in_features=1024, out_features=83, bias=True)
Lafzi Matlab: Aapka "Final Judge" (Fully Connected layer) tayyar hai.

Numbers ka Impact:

in_features=1024: Ye LSTM se 1024 details lega.

out_features=83: Ye un details ko wapas 83 scores mein badal dega (Har character ke liye aik score).

bias=True: Iska matlab hai model ko thori si "extra flexibility" di gayi hai taake woh behtar faisle kar sake.

Deep Learning Concept: Ye layer LSTM ki complex soch ko "Human-readable" characters mein convert karti hai.

# Converting a character in 256D Vector
"""

import torch
import numpy as np

# 1. Device check (Ferrari vs Cycle wala concept)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# 2. Aik choti si Dictionary (char_to_idx) bna lete hain agar pehle se nahi hai
# MIT course mein aksar ye 'vocab' se banti hai
try:
    # Agar char_to_idx pehle se hai to theek, warna ye error dega
    char_index = char_to_idx['a']
except NameError:
    # Dummy dictionary sirf test karne ke liye
    vocab = ['a', 'b', 'c', 'd', 'e', '|', '1', '2']
    char_to_idx = {ch: i for i, ch in enumerate(vocab)}

# 3. Model check: Kya aapne model pehle define kiya hai?
# Agar 'model' nahi mila to ye code crash karega.

char_to_look = 'a'

if char_to_look in char_to_idx:
    idx = char_to_idx[char_to_look]

    # [idx] ko tensor banaya
    input_tensor = torch.tensor([idx]).to(device)

    # Model ki embedding layer se 256-D vector nikala
    with torch.no_grad():
        # model.embedding hamari wahi layer hai jo summary mein dikhi thi
        vector_256d = model.embedding(input_tensor)

    print(f"--- Result ---")
    print(f"Character: '{char_to_look}' | Index: {idx}")
    # .cpu().numpy() isliye taake asani se print ho jaye
    print(f"Vector (Personality):\n{vector_256d.cpu().numpy()}")
else:
    print(f"Ghalti: '{char_to_look}' dictionary mein nahi hai!")

"""# Test out the RNN model"""

# Test the model with some sample data
x, y = get_batch(vectorized_songs, seq_length=100, batch_size=32)
x = x.to(device)
y = y.to(device)

pred = model(x)
print("Input shape:      ", x.shape, " # (batch_size, sequence_length)")
print("Prediction shape: ", pred.shape, "# (batch_size, sequence_length, vocab_size)")

sampled_indices = torch.multinomial(torch.softmax(pred[0], dim=-1), num_samples=1)
sampled_indices = sampled_indices.squeeze(-1).cpu().numpy()
sampled_indices

"""Pehli Line: Probability nikalna aur Chun-na 🎲
Python

sampled_indices = torch.multinomial(torch.softmax(pred[0], dim=-1), num_samples=1)
torch.softmax: Ye ek bahut zaroori function hai. Model jo pred (predictions) deta hai, wo raw numbers (logits) hote hain. softmax un numbers ko 0 se 1 ke darmiyan badal deta hai taake wo "Probabilities" (imkanaat) ban jayen. In sab ka total 1 hota hai. 📊

pred[0]: Hum poore batch mein se sirf pehle gaane (index 0) par kaam kar rahe hain.

dim=-1: Ye batata hai ke softmax aakhri dimension (vocab_size) par apply karna hai.

torch.multinomial: Ye sab se interesting word hai! Ye "Ratta" (Argmax) ke bajaye Randomly ek option chunta hai, lekin un options ko zyada chance deta hai jinki probability zyada ho.

num_samples=1: Hum keh rahe hain ke har step par sirf aik note select karo.

2. Dusri Line: Data ko Saaf Karna 🧹
Python

sampled_indices = sampled_indices.squeeze(-1).cpu().numpy()
.squeeze(-1): Kabhi kabhi data ke saath extra khali dimensions aa jati hain (jaise [[5]] ki bajaye [5]). squeeze un extra dimensions ko khatam kar ke data ko seedha kar deta hai.

.cpu(): Agar aapka data GPU par hai, to usay wapas Computer ke processor (CPU) par lana parta hai taake hum usay dekh saken.

.numpy(): Ye data ko PyTorch format se nikal kar NumPy array mein badal deta hai, jo Python mein handle karna asaan hai.

Explanation (Angrezi se Urdu/Hindi Mein) 💡
Aapki bheji gayi explanation mein ek bohat zaroori point hai: "Argmax vs Sampling".

Argmax: Iska matlab hai hamesha wo note chun-na jiska score sab se zyada ho. Iska nuksan ye hai ke model "Repetitive Loop" mein phans jata hai (yani ek hi dhun bar bar bajata rehta hai). 🔁

Sampling: Ye model ko thori "Azadi" deta hai. Agar kisi note ka chance 80% hai aur dusre ka 15%, to kabhi kabhi model 15% wale ko bhi chun lega. Is se music mein Variety aati hai. 🎼
"""

print("Input: \n", repr("".join(idx2char[x[0].cpu()])))
print()
print("Next Char Predictions: \n", repr("".join(idx2char[sampled_indices])))

"""Pichla Output vs Ye Wala Output 🔄
Pehle ye farq samjhein:

Pichla Output (Array): Ye computer ki zaban thi. Wo sirf numbers (indices) samajhta hai. 🔢

Ye Wala Output (String): Humne un numbers ko idx2char dictionary ke zariye characters mein badal diya hai taake insaan parh saken. 🔡

Ye Output itni ajeeb ("Gibberish") kyun hai? 😵‍💫
Aapne dekha ke input mein saaf saaf music notes (ABC notation) hain jaise ece|edB, lekin prediction mein ajeeb se symbols hain jaise b"caOQ>T'j3z. Iski 3 bari wajoohaat (reasons) hain:

Untrained Model: Yaad hai humne code ke shuru mein likha tha "Untrained model"? Iska matlab hai is model ne abhi tak music seekha hi nahi hai. Ye bilkul aisa hai jaise kisi bache ko pehli baar kalam pakra di jaye aur wo sirf lakeeren (scribbles) mare. 👶✍️

Random Initialization: Jab model banta hai, to uske andar ki "nasein" (weights) bilkul random hoti hain. Is liye uski predictions bhi bilkul random hoti hain.

Sampling: Humne multinomial sampling use ki hai, jo model ko thori azadi deti hai. Chunke model abhi "anari" hai, wo kisi bhi character ko utha kar predict kar raha hai.

# Training the model: loss and training operations
Training Loop: Model ko sikhane ka waqt 🏃‍♂️
Ab hum us part par aa gaye hain jahan model asal mein seekhta hai. Isay Training Loop kehte hain. Isme 4 main steps baar baar dohraaye jaate hain:


*   Forward Pass: Model ko data dena aur usse prediction lena.
*   Loss Calculation: Ye dekhna ke model ne kitni ghalti ki.


*   Backward Pass (Backpropagation): Ghalti ka zimmedar kaunsi "nas" (weight) hai, ye dhoondna.

*   Optimizer Step: Un weights ko thora sa badalna taake agli baar ghalti kam ho.

Jab hum model ko train karte hain, to ye ek Classification Problem ban jata hai. Iska matlab hai ke har step par model ko ye chun-na hai ke agla character kaunsa hoga (maslan 'a', 'b', 'c', ya '|').

Yahan jo baatein batayi gayi hain, unhein aasan alfaaz mein dekhte hain:

1. Cross Entropy Loss (Ghalti Napne ka Formula) 📉
Model ko sikhane ke liye hamein use batana parta hai ke uski prediction asli jawab se kitni door hai. Iske liye hum CrossEntropyLoss istemal karte hain.

Logits: Ye model ke wo raw numbers hain jo usne predict kiye (abhi humne dekha tha ke ye ajeeb symbols de raha hai).

Labels (Targets): Ye wo asli characters hain jo music file mein maujood hain.

2. PyTorch ki Khoobi 🛠️
PyTorch ka CrossEntropyLoss do kaam ek saath kar deta hai:

Ye numbers ko probabilities mein badalta hai (Softmax).

Ye check karta hai ke sahi jawab wali probability kitni zyada ya kam hai (Negative Log Likelihood).

3. Code ki Line ka Matlab 💻
Aapne pichle message mein permute ka pucha tha. CrossEntropyLoss ko use karne ke liye shapes ka sahi hona lazmi hai:

PyTorch ki requirement: Wo chahta hai ke vocab_size (classes) dusre number par ho.

Hamari prediction: (batch_size, sequence_length, vocab_size) yani (32, 100, 88).

Permute ke baad: (32, 88, 100).

Junior Role Interview Practice 💡
Question: "Music generation mein hum CrossEntropyLoss kyun use karte hain, Mean Squared Error (MSE) kyun nahi?"

Answer: MSE aam taur par numbers (Regression) ke liye hota hai. Music generation mein hum characters ya notes predict kar rahe hain jo alag-alag Classes hain. Jab bhi classes mein se sahi class chun-ni ho, to CrossEntropyLoss behtareen rehta hai.
"""

### Defining the loss function ###

# '''TODO: define the compute_loss function to compute and return the loss between
#     the true labels and predictions (logits). '''
cross_entropy = nn.CrossEntropyLoss() # instantiates the function
def compute_loss(labels, logits):
    """
    Inputs:
      labels: (batch_size, sequence_length)
      logits: (batch_size, sequence_length, vocab_size)

    Output:
      loss: scalar cross entropy loss over the batch and sequence length
    """

    # Batch the labels so that the shape of the labels should be (B * L,)
    batched_labels = labels.view(-1)

    ''' TODO: Batch the logits so that the shape of the logits should be (B * L, V) '''
    batched_logits = logits.view(-1, logits.size(-1))
    # batched_logits = """ TODO """ # TODO

    '''TODO: Compute the cross-entropy loss using the batched  next characters and predictions'''
    loss = cross_entropy(batched_logits, batched_labels)
    # loss = """ TODO """ # TODO
    return loss

"""Loss Function ko Instantiate Karnacross_entropy = nn.CrossEntropyLoss()nn.CrossEntropyLoss(): Ye PyTorch ka ek "Class" hai jo classification ke liye loss calculate karti hai. Humne iska ek object (cross_entropy) bana liya hai taake hum isay baar baar use kar saken. 🛠️2. Function Definitiondef compute_loss(labels, logits):labels: Ye hamara "Ground Truth" hai (asli sahi characters). Iski shape (batch_size, sequence_length) hai. 🎯logits: Ye model ki raw predictions hain. Iski shape (batch_size, sequence_length, vocab_size) hai.3. Labels ko Flatten Karnabatched_labels = labels.view(-1).view(-1): PyTorch mein iska matlab hai "jitne bhi numbers hain, un sab ko ek hi dimension mein set kar do".Natija: Agar hamare paas 32 batches aur 100 length thi ($32 \times 100 = 3200$), to ab batched_labels ki shape sirf (3200,) reh jayegi.Ab Asli Masla: Logits ki Shape 📐PyTorch ka CrossEntropyLoss do tarah se kaam karta hai:Ya to aap use High-Dimensional data dein (jahan classes 2nd dimension par hon).Ya phir aap use 2D matrix dein jahan har row ek prediction ho.


Logits ko Reshape Karna 📐
batched_logits = logits.view(-1, logits.size(-1))

logits.size(-1): Ye vocab_size (V) ko pakadta hai. Hamare case mein ye 88 (piano keys) hai.

.view(-1, ...): Pehle humne labels ko ek lambi line (B * L) bana diya tha. Ab hum logits ko bhi waisa hi kar rahe hain, lekin har "spot" par 88 numbers rakh rahe hain.

Natija: Iska size (3200, 88) ho jayega. Yani 3200 alag-alag predictions, aur har prediction ke liye 88 options ka score.

2. Loss Calculate Karna 📉
loss = cross_entropy(batched_logits, batched_labels)

cross_entropy: Ye wo "judge" 👨‍⚖️ hai jise humne upar define kiya tha.

Kaam: Ye batched_logits (model ka guess) ko leta hai aur dekhta hai ke batched_labels (asli sahi jawab) usme kis jagah par hai.

Math: Agar sahi jawab wale index par model ne bada number diya hai, to loss kam hoga. Agar wahan chota number hai, to loss zyada hoga.

Interview Question & Answer 💡
Question: "Humne training ke waqt view(-1) ya flatten kyun kiya?"

Answer: PyTorch ka CrossEntropyLoss function aam taur par 2D input (N, Classes) mangta hai. Hamare paas data 3D tha (Batch, Sequence, Vocab). Isliye humne Batch aur Sequence ko aapas mein jor kar aik lambi "list of predictions" bana di taake loss function har character ka muqabla uske sahi label se kar sakay.
"""

### compute the loss on the predictions from the untrained model from earlier. ###
y.shape  # (batch_size, sequence_length)
pred.shape  # (batch_size, sequence_length, vocab_size)

'''TODO: compute the loss using the true next characters from the example batch
    and the predictions from the untrained model several cells above'''
example_batch_loss = compute_loss(y, pred)
# example_batch_loss = compute_loss('''TODO''', '''TODO''') # TODO

print(f"Prediction shape: {pred.shape} # (batch_size, sequence_length, vocab_size)")
print(f"scalar_loss:      {example_batch_loss.mean().item()}")

"""y.shape  # (batch_size, sequence_length)pred.shape  # (batch_size, sequence_length, vocab_size)Yahan sirf comment mein bataya gaya hai ke hamara Sahi Jawab (y) aur Model ki Prediction (pred) kis shakal mein hain.pred mein har note ke liye poori vocabulary (e.g., 88 notes) ke scores hote hain, isliye usme ek extra dimension (vocab_size) hoti hai.2. Loss Calculate Karna 📉example_batch_loss = compute_loss(y, pred)compute_loss: Ye wo function hai jo humne abhi banaya tha.Ye function kya karta hai? Ye model ki tukka-baazi (pred) ko asli music notes (y) se compare karta hai.Chunke model abhi "untrained" (jisne kuch seekha nahi) hai, isliye ye loss kafi High (bara) aayega.3. Result ko Print Karna 🖥️print(f"scalar_loss: {example_batch_loss.mean().item()}").mean(): Chunke batch mein 32 mukhtalif gaane hain, hum un sabka "Average" loss nikalte hain..item(): Ye PyTorch ka ek bahut aham method hai. Ye tensor (jo computer ki memory mein hota hai) ko ek simple Python number mein badal deta hai taake hum usay screen par parh saken.Asli Logic: Untrained Model ka Loss 🧠Jab model untrained hota hai, to wo bilkul Random Guessing (tukkay) karta hai.Deep learning ka ek rule hai: Agar aapka model bilkul random hai, to uska loss taqreeban $-\ln(1/VocabSize)$ hona chahiye. Piano music ke liye agar vocabulary 88 hai, to ye loss taqreeban 4.4 ke qareeb aayega. Agar aapka loss is range mein hai, to iska matlab hai ke aapka "Loss Function" sahi kaam kar raha hai! ✅Interview Question & Answer 💡Question: "Humne loss calculate karne ke baad .item() kyun lagaya?"Answer: PyTorch ke tensors ke saath direct math ya printing kabhi kabhi mushkil hoti hai kyunke wo GPU memory mein ho sakte hain. .item() us tensor ke andar maujood akele number (scalar) ko nikal kar ek normal float value bana deta hai, jo humein asani se nazar aa jati hai.
Batch Size	Ek saath kitne samples process ho rahe hain	32
Sequence Length	Ek sample mein kitne notes hain	100
Vocab Size	Total kitne qism ke unique notes/letters hain
"""

### Hyperparameter setting and optimization ###

vocab_size = len(vocab)

# Model parameters:
params = dict(
  num_training_iterations = 3000,  # Increase this to train longer
  batch_size = 8,  # Experiment between 1 and 64
  seq_length = 100,  # Experiment between 50 and 500
  learning_rate = 5e-3,  # Experiment between 1e-5 and 1e-1
  embedding_dim = 256,
  hidden_size = 1024,  # Experiment between 1 and 2048
)

# Checkpoint location:
checkpoint_dir = './training_checkpoints'
checkpoint_prefix = os.path.join(checkpoint_dir, "my_ckpt")
os.makedirs(checkpoint_dir, exist_ok=True)

"""num_training_iterations = 3000: Model kitni baar data ko dekh kar seekhega. Jitni zyada iterations, utna zyada waqt model "practice" karega. 🔁learning_rate = 5e-3: Ye sab se aham setting hai. Ye batati hai ke har ghalti ke baad weights ko kitna bariki se badalna hai. 5e-3 ka matlab hai $0.005$. 🤏embedding_dim = 256: Har character ko ek number ke bajaye 256 numbers ki ek vector (list) mein badla jayega taake model unke darmiyan rishte samajh sakay. 🧬hidden_size = 1024: Ye RNN/LSTM ke andar ke "dimagh" ka size hai. Jitna bara ye number hoga, model utni complex dhunain yaad rakh sakega. 🧠
checkpoint_dir = './training_checkpoints': Humne ek folder ka naam rakha hai jahan hum apna kaam save karenge. 📁

checkpoint_prefix = os.path.join(...): Ye us file ka pura rasta (path) aur naam tay kar raha hai. Iska matlab hai ke hamari save files ka naam my_ckpt se shuru hoga.

os.makedirs(..., exist_ok=True): Ye asliyat mein wo folder banata hai. exist_ok=True ka matlab hai ke agar folder pehle se bana hua hai, to ghalti (error) mat dena balkay agay barhna. ✅
"""

### Create a Comet experiment to track our training run ###

def create_experiment():
  # end any prior experiments
  if 'experiment' in locals():
    experiment.end()

  # initiate the comet experiment for tracking
  experiment = comet_ml.Experiment(
                  api_key=COMET_API_KEY,
                  project_name="6S191_Lab1_Part2")
  # log our hyperparameters, defined above, to the experiment
  for param, value in params.items():
    experiment.log_parameter(param, value)
  experiment.flush()

  return experiment

"""def create_experiment():: Hum ek naya function bana rahe hain. Iska maqsad ye hai ke jab bhi humein training shuru karni ho, hum isay call kar ke apni "tracking diary" active kar lein.

if 'experiment' in locals(): experiment.end():

locals() computer ki memory check karta hai. 🧠

Agar pehle se koi experiment (diary) khuli hui hai, to ye usay end() kar deta hai taake naya data purane data mein mix na ho jaye.

experiment = comet_ml.Experiment(...):

Ye line asliyat mein Comet ke server par ek naya "page" kholti hai.

api_key: Ye aapka password 🔑 hai jo aapke account ko pehchanta hai.

project_name: Ye aapke folder ka naam hai taake aapka sara kaam ek hi jagah mile.

for param, value in params.items()::

Ye ek loop hai. 🔄 Humne jo params (Hyperparameters) set kiye thay (jaise batch size, learning rate), ye unko ek-ek kar ke uthata hai.

experiment.log_parameter(param, value):

Ye un settings ko hamesha ke liye save kar leta hai. 📋 Iska faida ye hai ke agar 1 mahine baad bhi aap dekhen, to aapko yaad hoga ke "Us din learning rate kya tha?"

experiment.flush():

Iska matlab hai "foran bhej do". 📤 Ye saari information foran internet par Comet ke dashboard par bhej deta hai.

return experiment:

Ye function tayyar shuda experiment object wapas kar deta hai taake hum training ke dauran mazeed cheezein (jaise loss) is mein likh saken.

# Optimizers & Backpropagation
1. Optimizer Chun-na (The Guide) 🛠️
Optimizer ka kaam ye hota hai ke wo model ke weights ko check kare aur bataye ke unhein kis taraf badalna hai taake ghalti (loss) kam ho jaye.

Adam: Ye sabse popular hai kyunki ye smart hai aur jaldi seekhta hai.

Adagrad: Ye har weight ke liye alag se "learning rate" adjust karta hai.

2. Backpropagation (Ghalti ka Hisaab) 📉
Jab model prediction karta hai aur humein loss pata chalta hai, to hum loss.backward() call karte hain.

Iska matlab ye hai ke hum peeche ki taraf (backwards) ja kar ye dekhte hain ke model ke kis hisse (neuron) ne kitni bari ghalti ki. Isay PyTorch ka autograd system sambhalta hai.

3. Optimizer Step (Wazan Badalna) 🔄
Jab ghalti ka hisaab lag jata hai, to hum optimizer.step() use karte hain.

Ye step asliyat mein model ke parameters (weights) ko thora sa update kar deta hai taake agli baar ghalti kam ho.

Junior Role Interview Practice 💡
Question: "PyTorch mein optimizer.step() aur loss.backward() ke darmiyan kya talluq (relationship) hai?"

Answer: loss.backward() ghalti ka hisaab lagata hai (gradients calculate karta hai), jabke optimizer.step() us hisaab ke mutabiq model ke weights ko asliyat mein update karta hai. Inke baghair model kabhi seekh nahi payega.
"""

COMET_API_KEY = "nb70UBQI77F7RAR68p5njFEyz" # Key pehle define karein
experiment = create_experiment() # Phir experiment banayein

import torch
import torch.optim as optim
from tqdm import tqdm

# 1. API Key aur Experiment Setup 🔑
COMET_API_KEY = "nb70UBQI77F7RAR68p5njFEyz"
experiment = create_experiment()

# 2. Data Safety Check 🛡️
# Agar max index vocab_size se bada hua toh error ayega
max_val = vectorized_songs.max()
if max_val >= vocab_size:
    print(f"⚠️ Warning: Max index ({max_val}) is >= vocab_size ({vocab_size})!")
    vocab_size = int(max_val + 1) # Auto-adjusting vocab_size

# 3. Model aur Optimizer Initialization 🏗️
model = LSTMModel(vocab_size, params["embedding_dim"], params["hidden_size"])
model.to(device) # GPU par bhej rahe hain 🚀

optimizer = torch.optim.Adam(model.parameters(), lr=params["learning_rate"])

# 4. Train Step Function 🛠️
def train_step(x, y):
    model.train()
    optimizer.zero_grad() # Purane gradients saaf karein 🧼

    # Forward pass: predictions nikalna
    y_hat = model(x)

    # Loss calculate karna
    loss = compute_loss(y, y_hat)

    # Backward pass: ghaltiyon se seekhna
    loss.backward()
    optimizer.step() # Weights update karna

    return loss

# 5. Training Loop 🔄
history = []
plotter = mdl.util.PeriodicPlotter(sec=2, xlabel='Iterations', ylabel='Loss')

if hasattr(tqdm, '_instances'): tqdm._instances.clear()

for iter in tqdm(range(params["num_training_iterations"])):

    # Batch hasil karna
    x_batch, y_batch = get_batch(vectorized_songs, params["seq_length"], params["batch_size"])

    # Tensors mein convert karke GPU par bhejna
    x_batch = torch.as_tensor(x_batch, dtype=torch.long).to(device)
    y_batch = torch.as_tensor(y_batch, dtype=torch.long).to(device)

    # Train step chalana
    loss = train_step(x_batch, y_batch)

    # Metrics log aur plot karna 📉
    experiment.log_metric("loss", loss.item(), step=iter)
    history.append(loss.item())
    plotter.plot(history)

    # Checkpoint save karna
    if iter % 100 == 0:
        torch.save(model.state_dict(), checkpoint_prefix)

# Final save 💾
torch.save(model.state_dict(), checkpoint_prefix)
experiment.flush()
print("Training Mukammal Ho Gayi! 🎉")

"""Model Instantiation (Model Banana) 🏗️
Python

model = LSTMModel(vocab_size, params["embedding_dim"], params["hidden_size"])
LSTMModel(...): Humne jo pehle model ka dhang (architecture) define kiya tha, ye usay asliyat mein "zinda" kar raha hai.

vocab_size: Model ko bataya ja raha hai ke total kitne unique notes ya characters hain (input/output layer ka size).

params["embedding_dim"]: Ye batata hai ke har character ko kitne baray vector mein convert karna hai (e.g., 256).

params["hidden_size"]: Ye LSTM ke "dimagh" ka size hai (e.g., 1024). Jitna bara ye hoga, model utni complex music patterns yaad rakh sakega.

model.to(device): Ye bohat ahem hai! Ye model ko GPU (graphics card) par bhej deta hai taake calculation fast ho sake. ⚡

2. Optimizer Setup (Ustad/Guide) 🔧
Python

optimizer = torch.optim.Adam(model.parameters(), lr=params["learning_rate"])
torch.optim.Adam: Hum "Adam" naam ka optimizer use kar rahe hain. Ye AI ki duniya ka sabse mashhoor optimizer hai kyunki ye bohat "smart" tareeqe se weights ko adjust karta hai.

model.parameters(): Hum optimizer ko batate hain ke usne model ke kaunse hisson ko badalna hai. Iska matlab hai "model ke saare weights ko update karo".

lr=params["learning_rate"]: Ye "Learning Rate" (seekhne ki raftar) hai. Ye tay karta hai ke har ghalti par weights ko kitna baray ya chote "qadam" se badalna hai.

Junior Role Interview Practice 💡
Question: "Agar hum model.to(device) karna bhool jayen lekin hamara data (batches) GPU par ho, to kya hoga?"

Answer: Code error de dega (RuntimeError). PyTorch mein ye lazmi hai ke Model aur Data dono ek hi jagah (yaani dono CPU par hon ya dono GPU par) hon, warna wo aapas mein math nahi kar paate.
model.train(): Ye model ko batata hai ke "Ab seekhne ka waqt hai!" 🏃‍♂️ Kuch layers (jaise Dropout) training aur testing mein mukhtalif behave karti hain, isliye ye command lazmi hai.

optimizer.zero_grad(): Jaisa ke humne baat ki, ye purani ghaltiyon ka record saaf kar deta hai taake naye batch ka hisaab bilkul fresh ho. 🧼

y_hat = model(x): Ye Forward Pass hai. Model input x (music notes) ko dekhta hai aur prediction y_hat (agla note kya hoga) karta hai.

loss = compute_loss(y, y_hat): Hum model ki prediction (y_hat) ko asli note (y) se compare karte hain taake pata chale ke model kitna "galat" hai. 📉
model.train(): Ye model ko "Training Mode" mein dalta hai. Iska matlab hai ke model ko pata chal jaye ke ab use apne weights update karne hain. 🏗️

optimizer.zero_grad(): Har baar naya sabak shuru karne se pehle purani baatein bhulani parti hain. Ye command pichli ghaltiyon (gradients) ko saaf kar deti hai taake naya batch asar-andaz na ho. 🧼

y_hat = model(x) (Forward Pass): Model input x ko dekhta hai aur apna andaza (prediction) y_hat deta hai. ⏩

loss = compute_loss(y, y_hat): Hum dekhte hain ke model ka andaza (y_hat) asli jawab (y) se kitna door hai. Jitna zyada loss, utni bari ghalti. 📉

loss.backward() (Backpropagation): Ye sabse "magic" wala step hai. PyTorch peeche ki taraf (backward) jata hai aur dekhta hai ke kis "neuron" ya weight ne kitni ghalti ki. 🧠

optimizer.step(): Jab ghalti ka pata chal jata hai, to optimizer model ke weights ko thora sa badal deta hai taake agli baar loss kam ho jaye. ✅
history = []:

Ye ek khaali List 📋 hai. Iska maqsad ye hai ke training ke dauran har step par jo "Loss" (ghalti) aayegi, usay hum yahan save karte jayenge taake baad mein graph bana saken.

plotter = mdl.util.PeriodicPlotter(...):

PeriodicPlotter: Ye ek tool hai jo training ke sath-sath graph banata hai.

sec=2: Iska matlab hai ke har 2 second baad graph ko update karo. ⏱️

xlabel / ylabel: Graph ki niche wali line (X) par "Iterations" likha hoga aur khari line (Y) par "Loss".

experiment = create_experiment():

Ye humne jo pehle function banaya tha usay Call 📞 kar raha hai. Ye Comet server par ek naya "Experiment" shuru kar deta hai taake hamari progress online save ho sake.

if hasattr(tqdm, '_instances'): tqdm._instances.clear():

tqdm: Ye wo progress bar ⏳ hai jo screen par chalti hui dikhti hai.

Ye line check karti hai ke agar pehle se koi purani progress bar "memory" mein phansi hui hai, to usay saaf (clear) kar do taake nayi bar sahi chale.

for iter in tqdm(range(params["num_training_iterations"])):

for iter in ...: Ye hamara main Loop 🔄 hai.

range(...): Ye loop itni bar chalega jitni humne iterations set ki hain (maslan 3000).

tqdm(...): Ye is loop ke gird ek progress bar lapait deta hai taake humein nazar aaye ke training kitne % mukammal ho gayi hai.
x_batch, y_batch = get_batch(...):

get_batch: Ye ek function hai jo hamare poore music data (vectorized_songs) mein se aik chota sa tukra (batch) nikalta hai. ✂️

x_batch: Ye model ka Input hai (music ka aik hissa).

y_batch: Ye model ka Target hai (yani wo agla note jo model ko predict karna chahiye).

seq_length: Ye batata hai ke ek baar mein kitne notes dikhane hain.

batch_size: Ye batata hai ke ek saath kitne muftalif sequences par training karni hai.

torch.tensor(..., dtype=torch.long):

Abhi tak data Numpy format mein tha. PyTorch model ko samajhne ke liye ise Tensor 🧊 mein badalna zaroori hai.

dtype=torch.long: Hamare notes integers (0, 1, 2...) hain, isliye hum "long" data type use karte hain.

.to(device):

Ye command hamare data ko GPU (graphics card) par bhej deti hai. 🚀 Model GPU par chal raha hai, isliye data ka wahan hona lazmi hai taake calculation tezi se ho sake.

loss = train_step(x_batch, y_batch):

Yahan hum apna banaya hua train_step function call kar rahe hain.

Model input leta hai, ghalti (loss) nikalta hai, aur Backpropagation ke zariye apne aap ko behtar banata hai. ✨
experiment.log_metric("loss", loss.item(), step=iter):

experiment: Hamara Comet object (wo digital diary jo humne banayi thi).

log_metric: Ye ek khas function hai jo aisi values ko save karta hai jo training ke dauran badalti rehti hain (jaise loss ya accuracy).

"loss": Hum Comet ko bata rahe hain ke is column ka naam "loss" rakho.

loss.item(): loss abhi ek PyTorch tensor hai. .item() usme se sirf number (e.g., 0.5) nikal leta hai taake wo asani se save ho sake.

step=iter: Ye batata hai ke ye loss kaunse step (iteration) ka hai.

history.append(loss.item()):

history: Wo khaali list jo humne training se pehle banayi thi.

append: Ye har naye loss ko list ke aakhir mein jorta jata hai taake hamare paas poori training ka record jama ho jaye.

plotter.plot(history):

plotter: Hamara PeriodicPlotter tool.

plot: Ye command history list ko uthati hai aur foran screen par ek graph bana deti hai. Is se humein live nazar aata hai ke loss neechay ja raha hai.

Log kyun liya hai? 🧐
Aapne poocha ke yahan "Log" kyun liya gaya hai. AI ki duniya mein "Logging" ka matlab hai "Record rakhna".

Agar hum sirf print(loss) karte, to loss screen par aata aur upar chala jata. Lekin humne log_metric isliye kiya taake:

History Save ho: Comet par hamara sara data save ho jaye.

Visual Graphs: Comet khud-ba-khud in numbers se khoobsurat graphs bana sake.

Comparison: Hum baad mein dekh saken ke "Kal wali training ka loss behtar tha ya aaj wali ka?"
1. Checkpoints: Beech-beech mein save karna 🚩
Python

if iter % 100 == 0:
    torch.save(model.state_dict(), checkpoint_prefix)
if iter % 100 == 0: Ye condition check karti hai ke kya humne mazeed 100 iterations mukammal kar li hain.

torch.save: Ye PyTorch ka function hai jo model ko file mein save karta hai.

model.state_dict(): Ye model ke saare seekhe hue Weights aur Parameters ka ek "snapshot" (photo) hai. 📸 Hum poora model save karne ke bajaye sirf ye weights save karte hain kyunki ye zyada efficient hai.

checkpoint_prefix: Ye us file ka rasta (path) hai jahan data save hoga.

Faida: Agar training ke dauran light chali jaye ya internet band ho jaye, to hamare paas har 100 steps ka record maujood hoga aur hum shuru se shuru nahi karna parega.

2. Final Save: Aakhri natija 🏆
Python

torch.save(model.state_dict(), checkpoint_prefix)
Jab loop khatam ho jata hai, to hum ek aakhri baar model ko save karte hain. Ye hamara Final Trained Model hota hai jo 3000 steps ke baad sabse zyada "samajhdar" hota hai.

3. Experiment Flush: Data bhejna 📤
Python

experiment.flush()
flush(): Iska matlab hai "dhakka dena". Kabhi kabhi Comet ka data buffer mein ruk jata hai. Ye command yaqini banati hai ke loop ke aakhir tak ka saara data (loss, graphs, parameters) foran Comet ke server par bhej diya jaye taake aapka dashboard 100% update ho jaye.
"""

### Prediction of a generated song ###

def generate_text(model, start_string, generation_length=1000):
  # Evaluation step (generating ABC text using the learned RNN model)

  '''TODO: convert the start string to numbers (vectorize)'''
  input_idx = [char2idx[s] for s in start_string] # TODO
  # input_idx = ['''TODO''']
  input_idx = torch.tensor([input_idx], dtype=torch.long).to(device)

  # Initialize the hidden state
  state = model.init_hidden(input_idx.size(0), device)

  # Empty string to store our results
  text_generated = []
  tqdm._instances.clear()

  for i in tqdm(range(generation_length)):
    '''TODO: evaluate the inputs and generate the next character predictions'''
    predictions, state = model(input_idx, state, return_state=True)
    # predictions, hidden_state = model('''TODO''', '''TODO''', return_state=True)

    # Remove the batch dimension
    predictions = predictions.squeeze(0)

    '''TODO: use a multinomial distribution to sample over the probabilities'''
    input_idx = torch.multinomial(torch.softmax(predictions, dim=-1), num_samples=1)
    # input_idx = torch.multinomial('''TODO''', dim=-1), num_samples=1)

    '''TODO: add the predicted character to the generated text!'''
    # Hint: consider what format the prediction is in vs. the output
    text_generated.append(idx2char[input_idx].item()) # TODO
    # text_generated.append('''TODO''')


  return (start_string + ''.join(text_generated))

"""1. Function Start (Taiyari)
def generate_text(model, start_string, generation_length=1000):

Flow: Yahan system ko bataya ja raha hai ke gaana likhne wala "Writer" kaun hai (model), wo shuruat kahan se kare (start_string), aur kitna lamba likhe (generation_length).

2. Text to Numbers (Translation)
input_idx = [char2idx[s] for s in start_string]

Flow: Computer English/ABC characters nahi samajhta.

Example: Agar aapne start_string diya "A", aur dictionary mein 'A' ka number 5 hai, to ye line "A" ko nikal kar uski jagah number 5 rakh degi. Ab Writer ke paas numbers ki aik list aa gayi.

3. Making it AI-Ready (Tensor Conversion)
input_idx = torch.tensor([input_idx], dtype=torch.long).to(device)

Flow: * torch.tensor: Normal list ko AI ki "Riazi (Maths)" wali list mein badla gaya.

[input_idx]: Iske gird extra brackets lagaye taake model ko pata chale ke ye "Batch 1" hai.

.to(device): Data ko Laptop ke GPU (Graphics Card) par bhej diya taake calculation bijli ki tarah tez ho.

4. Memory Reset (Brain Initialization)
state = model.init_hidden(input_idx.size(0), device)

Flow: RNN (Recurrent Neural Network) ki apni aik yaddasht (Memory) hoti hai. Is line par Writer (Model) apne purane khayalat saaf kar raha hai aur aik Fresh Mind ke sath naya gaana shuru karne ke liye taiyar ho raha hai.
text_generated = []Empty Container: Aik khali basket taiyar ki ja rahi hai jisme model apne likhe hue characters (musical notes) rakhta jayega.for i in range(gen_length):The Cycle: Ye loop 1000 dafa (ya jitni length aapne di) chalega. Har feri (iteration) ka matlab hai aik naya character generate hona.predictions, state = model(input_idx, state, ...)Brain Processing: Model input_idx (maujooda word) aur state (purani yaddasht) ko leta hai. Model ka dimaag process karke predictions (aglay word ka andaza) deta hai.predictions = predictions.squeeze(0)Cleaning: Model output mein extra brackets [[...]] deta hai. squeeze unhein hata kar data ko simple list [...] bana deta hai taake hum selection kar saken.
"""

'''TODO: Use the model and the function defined above to generate ABC format text of length 1000!
    As you may notice, ABC files start with "X" - this may be a good start string.'''
generated_text = generate_text(model, start_string="X", generation_length=1000) # TODO
# generated_text = generate_text('''TODO''', '''TODO''', '''TODO''')

!apt-get install -y ffmpeg

### Play back generated songs ###

generated_songs = mdl.lab1.extract_song_snippet(generated_text)

for i, song in enumerate(generated_songs):
  # Synthesize the waveform from a song
  waveform = mdl.lab1.play_song(song)

  # If its a valid song (correct syntax), lets play it!
  if waveform:
    print("Generated song", i)
    ipythondisplay.display(waveform)

    numeric_data = np.frombuffer(waveform.data, dtype=np.int16)
    wav_file_path = f"output_{i}.wav"
    write(wav_file_path, 88200, numeric_data)

    # save your song to the Comet interface -- you can access it there
    experiment.log_asset(wav_file_path)

"""extract_song_snippet(generated_text)

extract: Nikalna.

snippet: Tukra.

Flow: AI ne jo boht saara text likha hai, ye function usmein se sirf woh hissay nikaalta hai jo aik mukammal gaana banate hain.

waveform = mdl.lab1.play_song(song)

waveform: Audio ki lehr (vibration).

play_song: Ye function ABC text ko "Synthesize" karta hai, yani usay digital awaaz mein tabdeel kar deta hai.

ipythondisplay.display(waveform)

display: Colab mein aik Audio Player (Play/Pause button) dikhata hai taake aap gaana sun saken.

np.frombuffer(waveform.data, dtype=np.int16)

frombuffer: Raw audio data ko "Numbers" (Numpy array) mein badalta hai taake file save ki ja sakay.

int16: Audio ki quality (bit-depth) batata hai.

write(wav_file_path, 88200, numeric_data)

write: File likhna.

88200: Ye Sample Rate hai (yani aik second mein kitne sound points hain).

experiment.log_asset(wav_file_path)

log_asset: Ye aapki audio file ko online platform (Comet) par upload kar deta hai taake aapka kaam hamesha ke liye save ho jaye.
"""

torch.save(model.state_dict(), "model.pt")